# docker-compose.yml
version: "3"
services:
  # Growth Book
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3200:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - APP_ORIGIN=http://localhost:3200
      - MONGODB_URI=mongodb://root:password@mongo:27017/
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
